### PR TITLE
Ghc 8.0.1

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
the GHC7.6.3 build fails because the `Cabal` used is old, and don't backtrack: https://travis-ci.org/phadej/scientific/builds/102316993

**Comment by phadej** [comment]
Also I made a revision on hackage https://hackage.haskell.org/package/scientific-0.3.4.4
http://matrix.hackage.haskell.org/package/scientific

**Comment by basvandijk** [comment]
Thanks and sorry for the long delay. Released as [0.3.4.5](http://hackage.haskell.org/package/scientific-0.3.4.5).

**Comment by phadej** [comment]
@basvandijk Thanks! 

One note: the new release was unnecessary as Hackage supports metadata revisions, and I did one for you.

If you compare the dependencies of:
- http://hackage.haskell.org/package/scientific-0.3.4.4
- http://hackage.haskell.org/package/scientific-0.3.4.5

They are the same.

Or alternatively, [the changes introduced in `0.3.4.5`](http://hdiff.luite.com/cgit/scientific/diff?id=0.3.4.5&id2=0.3.4.4) are the same as made [in revision to `0.3.4.4`](http://hackage.haskell.org/package/scientific-0.3.4.4/revisions/) which makes both versions virtually the same.

We would prefer revisions whenever possible. Less versions to consider will make dependency solvers' job easier. Also if for some reason bounds are incorrect, Hackage trustees have less version to check.

**Comment by basvandijk** [comment]
@phadej I see. I always understood Hackage revisions as a temporary measure until a fixed version was released. But I see your point that it should be used as a permanent solution. Thanks for pointing that out!

**Pull request merged**
