### PR TITLE
Publicly expose scientificP parser

### PR DESCRIPTION
**Pull request by shlok**
See https://github.com/basvandijk/scientific/issues/51.

### CODE REVIEW

**Comment by basvandijk** [comment]
Thanks! Could you also add some documentation?

It would also be good if we document the relationship between `readPrec` and `scientificP` so that users know skipping whitespace is not part of `scientificP`. As in:

```haskell
    -- | Note that `readPrec` is defined as:
    -- @readPrec = Read.parens $ ReadPrec.lift $ ReadP.skipSpaces >> 'scientificP'@
    readPrec = Read.parens $ ReadPrec.lift $ ReadP.skipSpaces >> scientificP
```

**Comment by shlok** [comment]
Hi @basvandijk. I added some documentation for `scientificP` and the `Read` instance. Feel free to suggest improvements. (I haven’t yet added the `readPrec` documentation that you suggested.)

**Comment by basvandijk** [comment]
The documentation is excellent. Thanks! Released as [scientific-0.3.5.0](http://hackage.haskell.org/package/scientific-0.3.5.0).

**Comment by shlok** [comment]
@basvandijk Nice! Thanks for your cooperation.

**Pull request merged**
